version: '2'
services:
  gatling-runner:
    image: 848625190772.dkr.ecr.us-east-2.amazonaws.com/gatling-runner:latest
    command: -r <s3 bucket>
    environment:
      - GATLING_NR_USERS=1
      - GATLING_MAX_DURATION=1
      - GATLING_RAMPUP_TIME=10
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/gatling-runner
        awslogs-region: us-east-2
        awslogs-stream-prefix: gatling-runner
